-- 018_pin_timezone.sql
--
-- Pins the database's session timezone to Asia/Kolkata.
--
-- WHY
-- ---
-- A surprising amount of this app's user-visible arithmetic is evaluated in whatever
-- timezone the PostgreSQL *server* happens to be configured with:
--
--   * compute_renewal_status()      (schema.sql) -- `p_expiry_date::date < CURRENT_DATE`
--   * renewals_view.days_remaining  (schema.sql) -- `expiry_date::date - CURRENT_DATE`
--   * the dashboard's period boundaries (server/src/routes/misc.ts) -- CURRENT_DATE and
--     date_trunc('week'|'month', CURRENT_DATE)
--
-- None of those say which timezone they mean. They inherit it from postgresql.conf, which
-- defaults to the host OS. On the development machine that is IST, so everything agreed and
-- the dependency was invisible. On a UTC host — which is the default for most CI runners and
-- cloud databases — CURRENT_DATE is a different calendar day for the first 5.5 hours of
-- every IST day.
--
-- That matters because server/src/serializers.ts derives the SAME values in TypeScript and
-- is explicitly IST (Intl with timeZone: 'Asia/Kolkata'), since Prisma 7 cannot read
-- renewals_view usefully. So on a UTC host the SQL and the TypeScript would disagree about
-- what "today" is: a renewal could read `overdue` in one place and `due_today` in the other,
-- and the dashboard's "today" bucket would cover a different day from the renewals list.
-- Nothing would error. The numbers would just quietly be wrong.
--
-- Setting it on the database rather than in the connection string means every consumer gets
-- it — Prisma, maintPool, the scheduler, psql, and any future service — instead of each one
-- having to remember.
--
-- Applies to NEW sessions; existing connections keep their current setting until they
-- reconnect. Uses current_database() so the same migration works for medcrm and medcrm_test.
--
-- ####################################################################################
-- IMPORTANT — set the timezone BEFORE schema.sql on a fresh install; do not rely on this
-- migration alone. See db/README.md step 0.
-- ####################################################################################
--
-- Partition bounds are stored as ABSOLUTE INSTANTS. The literal in
-- `FOR VALUES FROM ('2026-05-01')` is resolved using the session timezone at CREATE time,
-- so a partition created under IST and named lead_activities_2026_05 actually spans
-- 2026-04-30 18:30Z .. 2026-05-31 18:30Z. Verified directly:
--
--   IST session: FOR VALUES FROM ('2026-05-01 00:00:00+05:30') TO ('2026-06-01 00:00:00+05:30')
--   UTC session: FOR VALUES FROM ('2026-04-30 18:30:00+00')    TO ('2026-05-31 18:30:00+00')
--
-- The consequence: a database whose partitions were created under timezone A cannot have
-- new ones added under timezone B, because the month-aligned bounds no longer line up:
--
--   ERROR: partition "lead_activities_2026_04" would overlap partition "lead_activities_2026_05"
--
-- So on a database built under UTC (the default on most CI runners and cloud hosts),
-- applying THIS migration would make ensure_monthly_partition() start failing the next time
-- the scheduler creates a month — turning a silent inconsistency into a daily error.
--
-- What matters is CONSISTENCY, not which zone: a build that is UTC throughout works fine
-- (verified). This migration is therefore safe on a database that was ALREADY effectively
-- Asia/Kolkata — which is what it is for: pinning the value so it cannot drift later.
--
-- If you must change the timezone of an existing database, drop and recreate the empty
-- future partitions under the new zone. Check the real bounds first:
--
--   SELECT c.relname, pg_get_expr(c.relpartbound, c.oid)
--     FROM pg_class c JOIN pg_inherits i ON i.inhrelid = c.oid
--     JOIN pg_class p ON p.oid = i.inhparent
--    WHERE p.relname = 'lead_activities';

DO $$
BEGIN
  EXECUTE format('ALTER DATABASE %I SET timezone = %L', current_database(), 'Asia/Kolkata');
END $$;

-- Verify on a fresh session with:  SHOW timezone;   -- expect Asia/Kolkata
